language: python

python:
  - "3.6"

install:
  - pip install virtualenv
  - pip install flask
  - pip install Flask-Mail
  - pip install flask-WTF
  - pip install flask-sqlalchemy

jobs:
  include:
    - stage: "Tests"                # naming the Tests stage
      name: "Unit Tests"            # names the first Tests stage job
      script: ./unit-tests
    - script: ./integration-tests
      name: "Integration Tests"     # names the second Tests stage job
    - stage: deploy
      name: "Deploy to GCP"
      script: ./deploy
